Repository grpc/grpc.io, pull requests merged in 2021-04, with the labels that each got.

#746 Upgrade to Hugo 0.82.0
  netlify.toml
Labels: infrastructure

#751 Make CNCF shortcode a bit more generic
  layouts/shortcodes/home/cncf.html
Labels: infrastructure

#760 C# Basics tutorial: code excerpt updates
  content/en/docs/languages/csharp/basics.md
Labels: examples

#761 Config: taxonomyTerm --> term
  config.yaml
Labels: infrastructure

#762 Blog: C# future -- normalizing markdown
  content/en/blog/grpc-csharp-future.md
Labels: cleanup/refactoring
